import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Appointment Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className=" mt-3 py-4   max-w-[1600px] m-auto  flex flex-col">
             <Navbar/>
            <div className="flex-1">{children}</div> 

              
        </div>
       
      
     
       
      </body>
    </html>
  );
}
