import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Appointment Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en" className=" min-h-screen">
  <body
    className={`${geistSans.variable} ${geistMono.variable} bg-[rgba(19,22,25,1)] text-white antialiased min-h-screen`}
  >
    <h4 className=""></h4>
    {children}
  </body>
</html>

  );
}
